### PR TITLE
#109 Added support for the new Microsoft Edge browser

### PR DESCRIPTION
**Pull request by nmaves**
Take a look and let me know what you think.

### CODE REVIEW

**Comment by nmaves** [comment]
How about now?

**Comment by guignol** [comment]
@nmaves thanks a lot !

**Comment by HaraldWalker** [comment]
I'll deploy an update probably later today. Am adding a few other changes. 
Also added Edge mobile.

**Comment by guignol** [comment]
thanks @HaraldWalker

**Comment by HaraldWalker** [comment]
Available now as snapshot release: 
https://oss.sonatype.org/content/repositories/snapshots/eu/bitwalker/UserAgentUtils/1.17-SNAPSHOT/
I want to make a few more changes (smart tvs, tizen os,...) before releasing 1.17.

**Comment by mathifonseca** [comment]
Hi @HaraldWalker, I don't mean to hurry you, but I wanted to know if you have an estimate on the release of version 1.17. I maintain the Grails plugin that wrapps user-agent-utils and I need to start detecting Microsoft Edge detection asap :)

**Comment by HaraldWalker** [comment]
@mathifonseca I will have a look tomorrow. If I don't include any other changes then a release goes quickly. Tell me more about the Grails plugin. I'd be happy to link to it.

**Comment by guignol** [comment]
Already tested in production over multiple millions users in my side and it's working very well

**Comment by mathifonseca** [comment]
@HaraldWalker thanks very much for the update! here is the link to the plugin repo, feel free to take a look and comment anything :) https://github.com/mathifonseca/grails-browser-detection

**Comment by HaraldWalker** [comment]
@mathifonseca 1.17 has been released and I added a link to the grails plugin on my site. Please remove the maven repo text. https://raw.githubusercontent.com/HaraldWalker/user-agent-utils/mvn-repo/ is not being used any longer.

**Comment by mathifonseca** [comment]
Done @HaraldWalker, thanks!

**Pull request merged**
