### PR TITLE
Create Parameterized unit test and Fix some issues

### PR DESCRIPTION
**Pull request by pcollaog**
Create Parameterized unit test bases in BrowserTest and VersionTest.

+ Create TestClass per Browser for more isolated unit tests
+ Create Test for Version detect (parameterized) based in VersionTest
+ Upgrade junit version from 4.7 to 4.11

Fix some Issues #82 #92 #72

**TODO**: delete duplicated tests

### CODE REVIEW

**Comment by pcollaog** [comment]
This have a little bug in test, fixing

**Comment by pcollaog** [comment]
Fix some Issues #82 #92 #72

**Comment by HaraldWalker** [comment]
Sorry, but timing of these changes is not good. Just before you there was a pull request with changes to some of the same classes and due to the formatting that you changed merging this is a pain now. 
I would have also preferred individual pull requests instead of one with various kind of changes.

**Comment by pcollaog** [comment]
Sorry about that... but you have to work in code style just for avoid the bloody pain with merges.

I'll work in some performance issues, I have another changes with at least 90% more efficient :+1:

**Comment by HaraldWalker** [comment]
I've committed fixes for #75 #82 #86 and #92 to trunk today.

**Comment by pcollaog** [comment]
I will fix the merge

**Pull request closed without merging**
