### PR TITLE
Add support for Microsoft Edge 13

### PR DESCRIPTION
**Pull request by slieschke**
https://blogs.windows.com/msedgedev/2015/09/21/understanding-versions-in-an-evergreen-browser/

### CODE REVIEW

**Comment by slieschke** [comment]
Edge 13 has been [publicly released with the first major Windows 10 update](http://blogs.windows.com/msedgedev/2015/11/16/introducing-edgehtml-13-our-first-platform-update-for-microsoft-edge/).

I haven't added support for the mobile version of Edge 13 as I don't have access to a real mobile Edge 13 user agent string to add a test. Let me know if you're happy for me to add it in without a test.

**Comment by HaraldWalker** [comment]
I think it is safe to assume that edge mobile 13 would follow the edge mobile 12 pattern and it is unlikely to have any wrong matches, so I think it is safe enough to add without a real world example.

**Comment by slieschke** [comment]
Done. I've followed the existing pattern for other mobile browsers and not created a new individual entry for mobile Edge 13. I've left mobile Edge 12 to preserve compatibility.

**Comment by asRIA** [comment]
Can this be merged? Looks like right solution for increasing problem.

**Comment by HaraldWalker** [comment]
@asRIA merged and I will work on a new release this week.

**Comment by bysse** [comment]
Great news!
We're using your library in most of our games at [King](https://king.com) and it work like a charm.
Thanks

**Comment by asRIA** [comment]
@HaraldWalker Thank you!

**Comment by HaraldWalker** [comment]
1.19 has been released.

**Pull request merged**
