### PR TITLE
Port to .net (csharp)

### PR DESCRIPTION
**Pull request by thunderstumpges**
We ported to .net (csharp) both the classes and tests. Not sure if you want them in the main repository. We will volunteer to update the .net versions with additions to the java one on a minimum quarterly basis.

### CODE REVIEW

**Comment by thunderstumpges** [comment]
Would love a comment on this work. Just pushed an update that refreshes all the unit tests and code to align with v1.16. We've been using this in production for some time without issue. Cheers.

**Comment by guignol** [comment]
it's gonna be a pain to maintain as the regular expressions are duplicated from the Java version.
This is awesome but wouldn't it be nice to have a config file that contains the BROWSER + regex then load this file and build the Browser list. This way we will have only one reference for the 2 applications.
What do you think ?

**Comment by HaraldWalker** [comment]
Sorry, should have responded earlier. Am not interested. Better if you keep it as your own project.

**Comment by thunderstumpges** [comment]
Sounds good. We don't mind keeping up to date ourselves. Guess this can serve as a hint for others looking for a C#/.net version to check out our fork. Thanks for the work creating this, we've really gotten good use from it!

**Pull request closed without merging**
