### PR TITLE
speedup Browser.parseUserAgentString

### PR DESCRIPTION
**Pull request by pavelsher**
Browser.parseUserAgentString performed expensive String.toLowerCase() call for each browser in the list and for each child of the browsers.

### CODE REVIEW

**Comment by petchema** [comment]
In fact the checks for null and the conversions toLowerCase() can be factorized all the way to the top in all classes...
https://github.com/petchema/user-agent-utils/commits/trunk

**Comment by pgrinchenko** [comment]
This performance issue is relevant for us as well. We spend significant time in UA analysis and we had to reduce amount of data that we process. In general this is a good change.

**Comment by HaraldWalker** [comment]
@pavelsher could you review @petchema 's version? We now have two similar improvements. Both seem fine to me but I have very little time at the moment. I'd be happy to accept either solution and still got some other pull requests to review and consider for a next release.

**Comment by petchema** [comment]
Diffs may not be very easy to understand, as I did this quickly, and don't know your code formatting style, but basically I employed two transformations:
- store arrays of patterns in lowercase, so they don't need to be lowercased with every use (nothing fancy);
- for methods that looked like
ResultType analyzeString(String s) {
  if (s != null) {
    String lowercaseS = s.toLowerCase();
    return f(lowercaseS);
  }
  return someResultType;
}
I exposed f(String) as a new private method, that expects a non-null lowercased String as parameter; Then replaced calls to analyzeString()
... x = analyzeString(s); ...
with calls to f():
... if (s != null) {
      String lowercaseS = s.toLowerCase();
      x = f(lowercaseS);
...
Looks like a silly transformation, but when this is done for all the "lowest level" analyzeString functions, the calling methods should be refactorizable like
  if (s != null) {
    String lowercaseS = s.toLowerCase();
    return g(lowercaseS);
  }
  return anotherResultType;
themselves, so you can repeat the process one level up.
When you're done, the string to analyze is checked for null and converted to lowercase in the public method entry point, then flows from private method to private method without further checks for null or conversion to lowercase... So it's only checked and converted once

**Comment by pavelsher** [comment]
@HaraldWalker I merged my changes and @petchema changes into this pull request. Pull request is large, but you can safely ignore changes in javadoc (btw, keeping javadoc in GitHub is a bit inconvenient but that's another story).

**Comment by HaraldWalker** [comment]
Thanks @pavelsher . I will have a look ASAP.

**Comment by petchema** [comment]
It's a bit late, but I found the time to do a more careful version of the changes (no javadoc commits, more consistent naming and indentation): 
https://github.com/HaraldWalker/user-agent-utils/compare/trunk...petchema:factorize-tolowercase-clean

**Comment by HaraldWalker** [comment]
Version 1.16 just got released. Sorry, it took so long. I usually try to have a release every 3 months. Some of the changes this time went beyond the regular maintenance.

**Pull request merged**
