### PR TITLE
Add new browser: Yandex Browser

### PR DESCRIPTION
**Pull request by YuraShakhov**
example of user-agent:
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 YaBrowser/16.9.1.1221 Yowser/2.5 Safari/537.36

### CODE REVIEW

**Comment by panxiaohuan** [comment]
can we use 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 YaBrowser/16.9.1.1221 Yowser/2.5 Safari/537.36' to YaBrowser

**Comment by highfei2011** [comment]
hi, @panxiaohuan .
    I think that should not be achieved, because in this analysis, there is no information of this version.
[https://github.com/HaraldWalker/user-agent-utils/blob/trunk/src/main/java/eu/bitwalker/useragentutils/Browser.java]

**Comment by highfei2011** [comment]
Hi, @HaraldWalker .
   Good afternoon, can you recommend a new ua parsing tool? thank you very much!

**Comment by HaraldWalker** [comment]
@highfei2011 
Commercial solution: https://udger.com/

There are some open source alternatives, but I have not tried them myself, so can not make any recommendations. 
Have a look at: 
https://github.com/blueconic/browscap-java
https://github.com/ankushs92/Browscap4j
https://github.com/woothee/woothee-java

**Pull request closed without merging**
